#!/bin/bash

if [[ $# -eq 1 ]]; then
    if [ ! -d "$1" ]; then
        mkdir -p $1
    fi
    selected="$1"
else
    selected=$(find ~/dev ~/ufrgs/*/* ~/contest -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [[ -z $TMUX ]]; then
    if ! tmux has-session -t="$selected_name" 2> /dev/null; then
        tmux new-session -s "$selected_name" -c "$selected"
    else
        tmux a -t "$selected_name"
    fi
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t $selected_name

